# Setup
title:        豆丁的日常记录
tagline:      真相，从来只有参与的人知道
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       douding
  url:        http://douding.me 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown